server:
  port: 8888
spring:
    application:
      name: gustavo-config-server
    cloud:
      config:
        server:
          git:
            uri: https://github.com/gugotardi/gustavo-config-server
            #username: username
            #password: password
            default-label: main
            search-paths:
              - 'greeting-service*'
